.\" Process this file with
.\" groff -man -Tascii name.1

.TH GDS2VRML: "1" "December 2012"

.SH NAME
gds2vrml \- a program for converting a GDS2 file to a VRML scene file
.SH SYNOPSIS
gds2vrml [\-b] [\-c config.txt] [\-d] [\-e camera.pov] [\-h] [\-i input.gds] [\-o output.pov] [\-p process.txt] [\-q] [\-t topcell] [\-v]
.SH OPTIONS
.TP
.BR \-b
Output bounding box instead of layout to allow easier and quicker placing of the camera
.TP
.BR \-c
Specify config file
.TP
.BR \-d
Decompose polygons into triangles (use mesh2 object instead of prism)
.TP
.BR \-g
Generate a process file based on the input gds2 file (suppresses POV-Ray file generation)
.TP
.BR \-h
Display this help
.TP
.BR \-i
Input GDS2 file (stdin if not specified)
.TP
.BR \-o
Output VRML file (stdout if not specified)
.TP
.BR \-p
Specify process file
.TP
.BR \-q
Quiet output
.TP
.BR \-t
Specify top cell name
.TP
.BR \-v
Verbose output
