.\" Process this file with
.\" groff -man -Tascii name.1

.TH TOPED: "1" "September 2012"
.SH NAME
toped \- a cross-platform open source IC layout editor
.SH SYNOPSIS
toped [parameters] <tll_command_file>
.SH OPTIONS
.TP
.BR \-ogl_safe
Forces the usage of the basic renderer
.TP
.BR \-I<path>
Expands the search paths of the parser. Multiply parameters of this kind are acceptable. each of them shall contain a single path
.TP
.BR \-D<macro>
Defines a preprocessor macro. Can be used multiply times
.TP
.BR \-D<macro>=<replacement>
Defines a preprocessor macro. Can be used multiply times
.SH AUTHORS
Svilen Krustev <skr@toped.org.uk>
.br
Sergey Gaitukevich <gaitukevich@toped.org.uk>
.br
Armin Taschwer <analogcmos@gmx.net>
